### ISSUE TITLE
Option for blank line after description

### ISSUE THREAD

**Issue by captainhammy** [DanielNoord/pydocstringformatter#102]
Would it be possible to have an option to insert a blank line after the description, similar to the `--blank` option for [docformatter](https://github.com/PyCQA/docformatter)

```
def factorial(x):
    """Return x factorial.

    This uses math.factorial.
    """
    import math
    return math.factorial(x)
```

would get reformatted to

```
def factorial(x):
    """Return x factorial.

    This uses math.factorial.

    """
    import math
    return math.factorial(x)
```

**Comment by DanielNoord** [comment]
I have recently added a commit that makes it so that such lines get automatically removed.

But there is nothing stopping us from adding them again.
Just wondering, what is the reason for wanting an additional line? That might give me some inspiration for a sensible option name.

**Comment by captainhammy** [comment]
Sorry, totally missed your response Daniel!

It's mostly out of preference and I liked that the stale docformatter had the option though given that it's not had a release in a long time I probably wouldn't use it.

I think I will actually just omit this since it's probably less proper to have a useless new line in there at the end for my own readability preferences.
