### ISSUE TITLE
Unable to Install the package

### ISSUE THREAD

**Issue by Anurag-Pola** [DanielNoord/pydocstringformatter#103]
pip install pydocstringformatter gives the following error

ERROR: Could not find a version that satisfies the requirement pydocstringformatter (from versions: none)
ERROR: No matching distribution found for pydocstringformatter

Am I missing something?

**Comment by DanielNoord** [comment]
Which version of `python` is `pip` running on?

**Comment by Anurag-Pola** [comment]
Python 3.9

**Comment by DanielNoord** [comment]
Hmm could you give me the output of ``pip --version``?

**Comment by Anurag-Pola** [comment]
pip 21.2.4 from C:\JPMC\DEV\TMP\ds\tools\python3.9\latest\lib\site-packages\pip (python 3.9)

**Comment by DanielNoord** [comment]
Does ``pip download pydocstringformatter`` work?

**Comment by Anurag-Pola** [comment]
No, the same error shows up!

**Comment by DanielNoord** [comment]
That's weird. Could you try upgrading `pip`? The latest is `22.1`.

**Comment by DanielNoord** [comment]
And perhaps the output of `pip --list`.

**Comment by Anurag-Pola** [comment]
I have tried with updated pip, but no luck

pip --list gives this 

Usage:
  pip <command> [options]

no such option: --list

**Comment by DanielNoord** [comment]
Oops, sorry. `pip list` 😉

**Comment by Anurag-Pola** [comment]
WARNING: Ignoring invalid distribution -ip (c:\some-directories\data\python3.9\site-packages)

Package                            Version
---------------------------------- ---------
astroid                            2.11.2
atomicwrites                       1.4.0
attrs                              21.4.0
autoflake                          1.4
black                              22.3.0
certifi                            2021.10.8
cffi                               1.15.0
charset-normalizer                 2.0.12
click                              8.1.2
clickclick                         20.10.2
colorama                           0.4.4
connexion                          2.13.0
coverage                           6.3.2
cryptography                       36.0.2
dill                               0.3.4
distlib                            0.3.4
docformatter                       1.3.1
filelock                           3.6.0
Flask                              1.1.2
Flask-Testing                      0.8.0
gaianamingsystem-gaiafs-gtf-events 1.0.0a4
idna                               3.3
inflection                         0.5.1
isort                              5.10.1
itsdangerous                       2.0.1
Jinja2                             3.0.3
jsonpickle                         2.1.0
jsonschema                         4.4.0
lazy-object-proxy                  1.7.1
MarkupSafe                         2.1.1
mccabe                             0.7.0
more-itertools                     8.12.0
mypy-extensions                    0.4.3
packaging                          21.3
pathspec                           0.9.0
pip                                22.1
pipenv                             2022.3.28
platformdirs                       2.5.1
pluggy                             0.13.1
py                                 1.11.0
pycparser                          2.21
pycryptodome                       3.12.0
pyflakes                           2.4.0
PyJWT                              2.1.0
pylint                             2.13.4
pyparsing                          3.0.7
pyrsistent                         0.18.1
pytest                             4.6.8
pytest-cov                         3.0.0
pytest-randomly                    1.2.3
python-dateutil                    2.8.2
PyYAML                             6.0
requests                           2.27.1
setuptools                         61.3.1
simplejson                         3.17.6
six                                1.16.0
swagger-ui-bundle                  0.0.9
tomli                              2.0.1
typing_extensions                  4.1.1
untokenize                         0.1.1
urllib3                            1.26.9
virtualenv                         20.14.0
virtualenv-clone                   0.5.7
wcwidth                            0.2.5
Werkzeug                           2.0.2
wrapt                              1.14.0
yapf                               0.31.0

**Comment by DanielNoord** [comment]
Do you know how to setup a virtualenv? And if so, could you perhaps try to do so?

On Windows I think it goes like:
```
virtualenv venv
.\venv\Scripts\activate
```
And then
```
pip list
pip install pydocstringformatter
```

**Comment by Anurag-Pola** [comment]
Hey @DanielNoord Thank you for the assist, I just realized the issue, it was something specific to our organization

Apologies for wasting your time

Also can I close the issue directly?

**Comment by DanielNoord** [comment]
No worries! Happy to help!

Yeah, feel free to close the issue if you don't have any other questions!

**Comment by Anurag-Pola** [comment]
A small follow up question though

I was trying out docformatter package and there it was not preserving line breaks in docstring comments

Ex: 

Before

"""
param1 : some loooooooooooooooooooooooooooooooooooooooooong striiiiiiiiiiiiiing
param2 : some description
"""

After

"""
param1 : some loooooooooooooooooooooooooooooooooooooooooong
striiiiiiiiiiiiiiiiiiiiiiing param2 : some description
"""

I found this package while I was searching for a solution for preserving the line breaks

Does it preserve the line breaks??

**Comment by DanielNoord** [comment]
It will preserve line breaks to some degree. I need to work on https://github.com/DanielNoord/pydocstringformatter/issues/90 to allow setting the max line length for summaries, but basically in the version that is currently in development we do:
```python
"""
param1 : some loooooooooooooooooooooooooooooooooooooooooong striiiiiiiiiiiiiing
param2 : some description
"""
"""
param1 : some loooooooooooooooooooooooooooooooooooooooooong
striiiiiiiiiiiiiiiiiiiiiiing
param2 : some description
"""
```
_Note that you would need to use the --max-summary-lines option for this. Otherwise we would add a white line after 'long'. `pydocstringformatter` enforces the concept of summaries and descriptions as explained in the [PEP](https://peps.python.org/pep-0257/#multi-line-docstrings)._

However, we don't wrap descriptions (currently). So the following would also work:
```python
"""My function that does something.

param1 : some loooooooooooooooooooooooooooooooooooooooooong striiiiiiiiiiiiiing
param2 : some description
"""
"""My function that does something.

param1 : some loooooooooooooooooooooooooooooooooooooooooong striiiiiiiiiiiiiing
param2 : some description
"""
```

**Comment by Anurag-Pola** [comment]
OK Got it, Thank you for the information, I will reach out if I face any more issues!

**Comment by DanielNoord** [comment]
Note that the line-wrapping is not released yet (it will be part of `0.6.0`) so currently it won't even do the wrapping as explained above!

**Comment by Anurag-Pola** [comment]
Ohh Ok got it, is there any way I could help in getting that feature faster?

**Comment by DanielNoord** [comment]
I'm open to a PR that implements #90. https://github.com/DanielNoord/pydocstringformatter/pull/81/ is another PR that implements a new option so if you want to you could look into that!

**Comment by Anurag-Pola** [comment]
Sure, I'll try to contribute
