### ISSUE TITLE
Failing when reading argument from pyproject.toml file

### ISSUE THREAD

**Issue by ariasjose** [DanielNoord/pydocstringformatter#128]
I'm receiving the following error when using pyproject.toml config file:
Don't know if I'm providing the param in the right way.

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/pydocstringformatter/configuration/toml_parsing.py", line 32, in _parse_toml_option
    action = OPTIONS_TYPES[opt]
KeyError: 'max-summary-lines'
pydocstringformatter.utils.exceptions.UnrecognizedOption: Don't recognize option max-summary-lines

pyproject.toml ==>
[tool.pydocstringformatter]
max-summary-lines = 2

**Comment by DanielNoord** [comment]
Fixed and now available in `v0.6.2` which you should be able to download from `PyPI` in about a minute or so.
