### ISSUE TITLE
Emoji in run.py crashes using pre-commit python 3.8.10

### ISSUE THREAD

**Issue by orSolocate** [DanielNoord/pydocstringformatter#13]
Hey Daniel,
The emoji in the last `print` statement under `run.py` crashes when using Python version that does not support emojis.

`UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 42: character maps to <undefined>`

For example for my `Python 3.5.3`, Windows 10 Pro 64 bit.

Do we want to support older version of Python with this tool? If so maybe the print statement should be modified?

**Comment by Pierre-Sassoulas** [comment]
Actually I'm surprised it even runs in 3.5 as there are also walrus operators that are 3.8 only.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  Yeah, i double checked it and it actually fails on my Python 3.8.10... modified title issue.
This is the error:

```
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Or\.cache\pre-commit\repopujjp6wt\py_env-python3.8\Scripts\pydocstringformatter.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Or\.cache\pre-commit\repopujjp6wt\py_env-python3.8\lib\site-packages\pydocstringformatter\__init__.py", line 18, in run_docstring_formatter
    _Run(argv or sys.argv[1:])
  File "C:\Users\Or\.cache\pre-commit\repopujjp6wt\py_env-python3.8\lib\site-packages\pydocstringformatter\run.py", line 25, in __init__
    self._check_files(self.config.files)
  File "C:\Users\Or\.cache\pre-commit\repopujjp6wt\py_env-python3.8\lib\site-packages\pydocstringformatter\run.py", line 32, in _check_files
    self._format_files(filepaths)
  File "C:\Users\Or\.cache\pre-commit\repopujjp6wt\py_env-python3.8\lib\site-packages\pydocstringformatter\run.py", line 82, in _format_files
    print("Nothing to do! All docstrings are correct \U0001f389")
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 42: character maps to <undefined>
```
I also added a print statement to show which version runs in the `run.py` file which says: `3.8.10`

when I open python 3.8.10 through cmd and run:
```
print("Nothing to do! All docstrings are correct \U0001f389")
Nothing to do! All docstrings are correct 🎉
```
I get  no error...

**Comment by DanielNoord** [comment]
I need some time to explore this a bit further. The tests pass on Windows for `3.8.10` (see [here](https://github.com/DanielNoord/pydocstringformatter/runs/4694658441?check_suite_focus=true)) and do test this message.

I was inspired by `black` to add emoji's so I didn't expect many problems. This emoji is also quite old so it should be supported. There might be something specific going on for Windows, `codec` and encoding of emoji's. I'm not sure. I'll have a look!

**Comment by Pierre-Sassoulas** [comment]
There was a similar issue in tryceratops a while ago : https://github.com/guilatrova/tryceratops/issues/37

**Comment by DanielNoord** [comment]
Btw, the project was intended to only support 3.8+ to make use of assignment operators. Since I mainly work on `astroid` and `pylint` this isn't a big problem for me: development for those projects is encouraged to be done on 3.8+ as the `ast` parser is better on those versions.

If people really want this on older version we can obviously work on compatibility but that should probably done in another issue.

**Comment by DanielNoord** [comment]
For future reference: issue was identified here https://github.com/guilatrova/tryceratops/pull/33#issuecomment-939140782

**Comment by orSolocate** [comment]
@DanielNoord Adding this to `run.py` before the function runs solves it ~!~

```
sys.stdin.reconfigure(encoding='utf-8')
sys.stdout.reconfigure(encoding='utf-8')
```

Answer found [here](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters)

**Comment by DanielNoord** [comment]
Ah, thanks for this! I saw that `black` uses `click.echo` to print their emoji's. I'm going to look what they are doing as well! Perhaps they are also reconfiguring `sys.stdin`? Feels a bit weird though. Does that reconfigure persist after `run.py` finished?

**Comment by orSolocate** [comment]
If I got it right from the answer [here](https://stackoverflow.com/questions/16549332/python-3-how-to-specify-stdin-encoding), the stdin is only a buffer so modifying it does not influence the "outside world"

**Comment by DanielNoord** [comment]
@orSolocate I can't test this myself, but are you able to trigger this error through `pytest`? I'd like to add a test case for this, but I'm not quite sure how to do so considering that we currently don't fail any tests on Windows.

See: https://github.com/DanielNoord/pydocstringformatter/pull/16

**Comment by orSolocate** [comment]
`pytest` tests passed when I run them.. I think your solution in #16 is pretty good
