### ISSUE TITLE
Incorrect reading of pyproject.toml

### ISSUE THREAD

**Issue by jspaezp** [DanielNoord/pydocstringformatter#155]
Hello there!

I found a bug where the 'style' argument is ignored from the configuration file

This is my the section of my toml

```toml
[tool.pydocstringformatter]
style = "randomdoc"
exclude = [".tox/**"]
max-line-length = 88
```

After a little lurking I think it is caused by this ....

The style arg is defined as an extend.

https://github.com/DanielNoord/pydocstringformatter/blob/7a973217b2f99c61557ce7d6ad5a6a8b042d96d4/pydocstringformatter/_configuration/arguments_manager.py#L121-L128

And extend style args are not checked in the parsing of the toml file. Thus replacing whatever is in the field with
an empty list (which gets ignored later)

https://github.com/DanielNoord/pydocstringformatter/blob/7a973217b2f99c61557ce7d6ad5a6a8b042d96d4/pydocstringformatter/_configuration/toml_parsing.py#L44-L52

Possible fix:

changing the `pydocstringformatter/_configuration/toml_parsing.py#L44-L52` to ...

```python
 if isinstance(action, argparse._StoreTrueAction): 
     if value is True: 
         return [action.option_strings[0]] 
     return [] 
 elif isinstance(action, argparse._StoreAction): 
     if isinstance(value, int): 
         value = str(value) 
     return [action.option_strings[0], value] 
 elif isinstance(action, argparse._ExtendAction): 
     if isinstance(value, str): 
         value = str(value) 
     return [action.option_strings[0], value] 
 else:
    raise NotImplementedError
# return []  # pragma: no cover
```

so it **1** Checks for the extend type args and **2** makes maintaining the package easier because it throws an error instead of silently ignored wrongly parsed files.

btw ... debugging was not super easy to be honest, is there a way to have the cli return the configuration that will be used? (explicit version of all the configuration arguments) ... like `--verbose` argument.

Let me know if you would like me to make PR for any of these

Best!
Sebastian

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for the debugging and analyzing the issue ! PR are welcome, let's do one for each issue (easier debugging and the configuration bug) .
