### ISSUE TITLE
Bug, Index error when the last summary line is empty

### ISSUE THREAD

**Issue by jspaezp** [DanielNoord/pydocstringformatter#159]
Noticed that the software breaks when the last line of the summary line is empty

Breaking args:

        # Breaks >>> Call Args:  ['tests/data/format/quotes_type/module_docstring.py', '--style', 'numpydoc', '--strip-whitespaces']
        # Works >>> Call Args:  ['tests/data/format/quotes_type/module_docstring.py', '--style', 'numpydoc', '--no-strip-whitespaces']

Solution:

Modifying:

https://github.com/DanielNoord/pydocstringformatter/blob/c749fc62699443a784e3211ed9aa0d591134db6a/pydocstringformatter/_formatting/_utils.py#L1-L9

To:

```python
 import functools 
  
  
 @functools.lru_cache(maxsize=None) 
 def is_rst_title(summary: str) -> bool: 
     """Check if the second line of a summary is one recurring character.""" 
     # If second line is one recurring character we're dealing with a rst title 
     if len(last_line) == 0:
        return False
     last_line = summary.splitlines()[-1].lstrip() 
     return last_line.count(last_line[0]) == len(last_line) 

```

**Comment by DanielNoord** [comment]
I don't think your solution would work as `last_line` won't be defined at the `len` check, but please open a PR to fix the issue. This is indeed a bug.

**Comment by jspaezp** [comment]
my bad, it was copy/paste from my local fix
