### ISSUE TITLE
Check how ``BolleanOptionalActions`` should be registered in the namespace

### ISSUE THREAD

**Issue by DanielNoord** [DanielNoord/pydocstringformatter#167]
They are registered differently ... cannot be done. I am not sure if there is any other less hacky way of getting that attribute.

This is what i get if i start a debugger in line 278
```python
(pdb) p run.config.__dict__.keys()
dict_keys([..., 'max_summary_lines', ... 'numpydoc-section-order', ...])
(pdb) p run.config.strip_whitespace
*** AttributeError: 'Namespace' object has no attribute 'strip_whitespace'
```

_Originally posted by @jspaezp in https://github.com/DanielNoord/pydocstringformatter/pull/166#discussion_r970549818_

**Comment by DanielNoord** [comment]
Closing.

See https://stackoverflow.com/questions/12834785/having-options-in-argparse-with-a-dash

This is just a quick of `argparse`. Patching this behaviour to replace `-` with `_` will always lead to other places where you would need to do the conversion the other way around. I think it's best to just follow `argparse` here and occasionally access `__dict__`.

**Comment by jspaezp** [comment]
note: an alternative sentence if accessing the internal dict is not desired: getattr(args, 'positional-arg')
