### ISSUE TITLE
Solve/diagnose conflicting formatters

### ISSUE THREAD

**Issue by jspaezp** [DanielNoord/pydocstringformatter#169]
Started discussion in PR #162 

https://github.com/DanielNoord/pydocstringformatter/pull/162#issuecomment-1248796789

Pitch: Passing over the formatters twice could help clear out problems where the work of one formatter is undone by another one.

The current implementation is mostly focused in finding that formatters conflict with each other (run again after a full pass)
and having it raise an error.

Current development branch ...
https://github.com/jspaezp/pydocstringformatter/tree/feature/twopass

Current broken tests ...

```
FAILED tests/test_config.py::TestStyleOption::test_style_in_toml - ValueError: Conflicting formatters: numpydoc-section-spacing, closing-quotes
FAILED tests/test_config.py::TestStyleOption::test_boolopt_in_toml - ValueError: Conflicting formatters: numpydoc-section-spacing, closing-quotes
FAILED tests/test_formatting.py::test_formatting[linewrap_summary-function_docstrings.py] - ValueError: Conflicting formatters: split-summary-body, final-period
FAILED tests/test_formatting.py::test_formatting[linewrap_summary-max_line_length_50.py] - ValueError: Conflicting formatters: split-summary-body, final-period
FAILED tests/test_formatting.py::test_formatting[numpydoc-numpydoc_regression.py] - ValueError: Conflicting formatters: numpydoc-section-spacing, closing-quotes
```

so .... is it of interest to add this changes? If anything it is a great debugging addition for development
should arguments be added to enable it?
should the error be more user-friendly?

If so and you have insights on those design aspects I will make this a PR

**Comment by DanielNoord** [comment]
I haven't looked at your branch as I am on mobile, but I'm highly in favour of this change. I'll gladly help review a PR but sadly won't have time to work on this myself this week. 

Some pointers to consider:
- I think the maximum run count should be 2. 
- After the second run, a third run should occur. If we still create changes (note that these should ignore the --write flag but should only check if there are any potential change) we need to emit an error. `black` has a very elegant system where after there is an inconsistency aftwr 2/3 runs a pre-regenerated bug report is send to stdout. This can then be copied to an issue in GitHub which would allow us to resolve the issue.
- We should test the issue template. So we need to write two incompatible test formatters and write a test where they fail to find a solution.

That's all I can think of for now. Let me know if you have any questions! 😊
