### ISSUE TITLE
Option to disable the sucess message 'Nothing to do! All docstrings are correct'

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [DanielNoord/pydocstringformatter#22]
When used with pre-commit everything is parallelized, so we get duplicate message for each batch that do not have any errors:
```
Formatted read_write.py 📖
Nothing to do! All docstrings are correct 🎉
Nothing to do! All docstrings are correct 🎉
Nothing to do! All docstrings are correct 🎉
```
This disable option should be activated in the default pre-commit configuration.

**Comment by DanielNoord** [comment]
Shouldn't this be fixed by setting `require_serial` true in our `hooks.yaml`? See https://pre-commit.com

**Comment by Pierre-Sassoulas** [comment]
Well, yes but parallelism is a feature that makes pre-commit faster, disabling it isn't ideal.

**Comment by DanielNoord** [comment]
Let's make a `--verbose` and `--quiet` option, with the latter not printing anything and the former only printing when something changes.
