### ISSUE TITLE
Set a ``notes-rgx=`` pattern in pylint to allow ``TODO(#24)`` 

### ISSUE THREAD

**Issue by DanielNoord** [DanielNoord/pydocstringformatter#24]
I find it pretty annoying to keep having to add `disable=fixme` everywhere but I like to enable the checker.

I think it would be very good to allow ``TODO`` comments that specify a related follow-up issue number. So, taking this issue as example:

```python
# TODO: Fix how fixme is interpreted      # bad

# TODO(#24): Fix how fixme is interpreted      # good
```

At some point we could even add a test that verifies whether the issue actually exists, but that might be more difficult and creates a bit of a chicken-egg problem: you'll need to open a follow-up issue for a not yet approved PR. That also feels a bit weird..

**Comment by Pierre-Sassoulas** [comment]
Is this supposed to be an issue in pylint ? :)

**Comment by DanielNoord** [comment]
Possibly in the future 😄 

I'd like to experiment with it here!
