### ISSUE TITLE
Exit with correct exit codes

### ISSUE THREAD

**Issue by DanielNoord** [DanielNoord/pydocstringformatter#4]
Currently the program does nothing with exit codes. This might be useful when it's used in combination with CIs.

**Comment by DanielNoord** [comment]
Just to record some thoughts on this. I was thinking of:
0 - Nothing happened, all files are fine.
1 - Internal error
2 - Config parsing error
4, 8, 16 - Empty for future use
32 - A file was changed or could be changed
64, 128, 256 - Empty for future use

**Comment by Pierre-Sassoulas** [comment]
Sounds great, but just exiting with 1 for everything except 'nothing to do all files are fine" would be ok too. I don't think the exit code will matter much.
