### ISSUE TITLE
Isolated `"""` counted toward limit of two summary lines

### ISSUE THREAD

**Issue by jacobtylerwalls** [DanielNoord/pydocstringformatter#86]
Can't remove the blank line at https://github.com/PyCQA/pylint/pull/6040/commits/f5b85a20b81f458232eae2afe862040a62bf1b10#r838122809

```python
    @staticmethod
    def _has_homonym_in_comprehension_test(node: nodes.Name) -> bool:
        """
        Return True if `node`'s frame contains a comprehension having

        an "if" test employing an identical name. The use of the name
        in the if test could come in several levels of nesting:

        Examples:
            [x for x in range(3) if name]
            [x for x in range(3) if name.num == 1]
            [x for x in range(3)] if call(name.num)]
        """
```

**Comment by DanielNoord** [comment]
That is "by design". `pylint` sets `"--max-summary-lines=2"`. This means that a summary (the first lines until the first whitespace) can only be 2.
This is already a deviation from the PEPs which argue that the summary should be one line.
In order not to have the tool be too frustrating we changed set it to 2 for `pylint`.

```python
    @staticmethod
    def _has_homonym_in_comprehension_test(node: nodes.Name) -> bool:
        """
        Return True if `node`'s frame contains a comprehension having
        an "if" test employing an identical name. 

        The use of the name in the if test could come in several levels of nesting:

        Examples:
            [x for x in range(3) if name]
            [x for x in range(3) if name.num == 1]
            [x for x in range(3)] if call(name.num)]
        """
```

This should work

**Comment by jacobtylerwalls** [comment]
Ah, just tried it and unfortunately it doesn't work.

**Comment by DanielNoord** [comment]
Hmm, one guess:
We might consider the `""" `  opening to be a line when counting summary lines. We shouldn't.. But we might 😄

**Comment by jacobtylerwalls** [comment]
Yeah that's it! It works with `"""starting like this`

**Comment by DanielNoord** [comment]
Thanks! I really hoped to make this tool not as annoying as most other auto-format tools can be. Guess we failed here 😅
